name: Java CI

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    submodules: true
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    distribution: 'adopt-hotspot'
                    java-version: '17'
                    cache: 'maven'
            -   name: Build with Maven
                run: mvn clean verify
            -   name: Upload coverage to Codecov
                uses: codecov/codecov-action@v3
                with:
                    fail_ci_if_error: true
                    verbose: false
