name: Java CI

on:
    push:
        branches:
            - master
    pull_request:
    pull_request_target:
        branches:
            - master

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    submodules: true
            -   name: Set up JDK 8
                uses: actions/setup-java@v2
                with:
                    java-version: 1.8
            -   name: Build with Maven
                run: mvn clean package
